version: '3.3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DHPARAM_GENERATION=false
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - "nginx-proxy"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
       - DEFAULT_EMAIL=cesarsanz91@gmail.com

  api:
    container_name: api
    image: localhost:5009/api
    build: ./python-api
    restart: always
    expose:
      - "5000"
    volumes:
      - ./python-api/logs:/app/logs
    env_file:
      - 'variables.env'
    secrets:
      - api_secrets
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      - INFLUXDB_HOST=influxdb
      - VIRTUAL_HOST=api.iotcloud.es
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.iotcloud.es
      - VIRTUAL_NETWORK=iotcloud-overlay-net

  influx_mqtt_gateway:
    container_name: gateway
    image: localhost:5009/gateway
    build: ./python-gateway
    env_file:
      - 'variables.env'
    restart: always
    volumes:
      - ./python-gateway/logs:/app/logs
    secrets:
      - gateway_secrets
    depends_on:
     - influxdb

  weather:
    container_name: weather
    image: localhost:5009/weather
    build: ./python-weather
    env_file:
      - 'variables.env'
    restart: always
    expose:
      - "5003"
    volumes:
      - ./python-weather/logs:/app/logs
    secrets:
      - weather_secrets

  modules:
    container_name: modules
    image: localhost:5009/modules
    build: ./python-modules
    env_file:
      - 'variables.env'
    restart: always
    volumes:
      - ./python-modules/logs:/app/logs
    secrets:
      - modules_secrets

  monitoring:
    container_name: monitoring
    image: localhost:5009/monitoring
    build: ./python-monitoring
    restart: always
    volumes:
      - ./python-monitoring/logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hostname:/app/hostname:ro
    env_file:
      - 'variables.env'

  home:
    container_name: home
    image: localhost:5009/home
    build: ./go-home
    env_file:
      - 'variables.env'
    restart: always
    expose:
      - "5001"
    volumes:
      - ./go-home/src:/app/src
      - ./go-home/logs:/app/logs
    secrets:
      - home_secrets
    environment:
      - VIRTUAL_HOST=home.iotcloud.es
      - VIRTUAL_PORT=5001
      - LETSENCRYPT_HOST=home.iotcloud.es
      - VIRTUAL_NETWORK=iotcloud-overlay-net

  grafana-datasource:
    container_name: grafana-datasource
    image: localhost:5009/grafana-datasource
    build: ./go-grafana-datasource
    env_file:
      - 'variables.env'
    restart: always
    expose:
      - "5002"
    volumes:
      - ./go-grafana-datasource/src:/app/src
      - ./go-grafana-datasource/logs:/app/logs
    secrets:
      - grafana_datasource_secrets

  grafana:
    user: "$UID:$GID"
    restart: always
    image: grafana/grafana:latest
    expose:
      - "3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config:/etc/grafana
      - ./certs:/grafana/certs
      - ./grafana/log:/var/log/grafana
    environment:
      - GF_INSTALL_PLUGINS=simpod-json-datasource 0.2.6
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID__FILE=/run/secrets/grafana_secrets_clientId
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE=/run/secrets/grafana_secrets_clientSecret
      - VIRTUAL_HOST=grafana.iotcloud.es
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.iotcloud.es
      - VIRTUAL_NETWORK=iotcloud-overlay-net
    secrets:
      - grafana_secrets_clientId
      - grafana_secrets_clientSecret

  mongodb:
    restart: always
    image: mongo:4.2.5
    hostname: docker
    volumes:
      - ./mongodb:/data/db
    expose:
      - "27017"
    command: mongod --setParameter diagnosticDataCollectionEnabled=false # --quiet

  influxdb:
    image: influxdb:1.8
    env_file:
      - 'variables.env'
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    expose:
      - "8086"
    restart: always

  mosquitto:
    image: jllopis/mosquitto
    restart: always
    volumes:
      - ./mosquitto/data:/var/lib/mosquitto
      - ./mosquitto/log:/var/log/mosquitto
      - ./mosquitto/config:/etc/mosquitto
      - ./mosquitto/mosquitto.d:/etc/mosquitto.d
      - ./nginx/certs/mqtt.iotcloud.es:/etc/mosquitto/certs:ro
    ports:
      - "8883:8883"
      - "1883:1883"
    expose:
      - "9001"
    environment:
      - VIRTUAL_HOST=mqtt.iotcloud.es
      - VIRTUAL_PORT=9001
      - LETSENCRYPT_HOST=mqtt.iotcloud.es
      - VIRTUAL_NETWORK=iotcloud-overlay-net

  telegraf:
    image: telegraf
    restart: always
    env_file:
      - 'variables.env'
    hostname: localhost
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./nginx/logs:/var/log/nginx:ro
      - ./python-modules/logs/modules.log:/var/log/modules/modules.log:ro
      - ./python-api/logs/server.log:/var/log/api/server.log:ro
      - ./python-monitoring/logs/monitoring.log:/var/log/monitoring/monitoring.log:ro
      - ./python-weather/logs/weather.log:/var/log/weather/weather.log:ro
      - ./mosquitto/log/mosquitto.log:/var/log/mosquitto/mosquitto.log:ro
      - ./go-home/logs/main.log:/var/log/home/main.log:ro
    depends_on:
     - influxdb
     - nginx-proxy

  ota:
    image: flashspys/nginx-static
    container_name: ota
    expose:
      - "5004"
    volumes:
      - ./ota/data:/static
    environment:
      - VIRTUAL_HOST=ota.iotcloud.es
      - VIRTUAL_PORT=5004
      - LETSENCRYPT_HOST=ota.iotcloud.es
      - VIRTUAL_NETWORK=iotcloud-overlay-net

secrets:
  modules_secrets:
      file: ./python-modules/secrets
  weather_secrets:
    file: ./python-weather/secrets
  home_secrets:
      file: ./go-home/secrets
  grafana_datasource_secrets:
      file: ./go-grafana-datasource/secrets
  api_secrets:
      file: ./python-api/secrets
  gateway_secrets:
      file: ./python-gateway/secrets
  grafana_secrets_clientId:
      file: ./grafana/secrets/clientId
  grafana_secrets_clientSecret:
      file: ./grafana/secrets/clientSecret
  
