version: '3.3'
services:
  grafana:
    user: $ID
    restart: always
    image: grafana/grafana:6.3.6
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config_dev:/etc/grafana
      - ./certs:/grafana/certs
      - ./grafana/log:/var/log/grafana